In [1]:
import tensorflow as tf

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[12, 21,  1, 96, 80],
       [83, 65, 74, 76, 27],
       [61, 95, 73, 27, 28],
       [21, 32, 96, 42, 24],
       [44, 74, 59, 13, 34]])>

# Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor.

In [4]:

random_tensor=tf.random.uniform(shape=(5,5), minval=1, maxval=100, dtype=tf.int32 )
random_tensor

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[54, 69, 55, 45, 88],
       [48, 46, 30, 80,  4],
       [26, 84, 46, 58, 58],
       [27, 17, 52, 19, 20],
       [33, 61, 69, 55, 64]])>

# Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor.

In [5]:
prime_tensor=tf.convert_to_tensor([[2,5,7,11,17],[3,13,19,29,23],[31,41,37,43,47],[2,5,7,41,43],[17,11,7,23,37]])
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 2,  5,  7, 11, 17],
       [ 3, 13, 19, 29, 23],
       [31, 41, 37, 43, 47],
       [ 2,  5,  7, 41, 43],
       [17, 11,  7, 23, 37]])>

# tampilan dari kedua variable diatas

In [20]:
from prettytable import PrettyTable
table=PrettyTable(['Nama', 'Dimensi'])
table.add_row(['random_tensor', random_tensor.shape])
table.add_row(['prime_tensor', prime_tensor.shape])
print(table)

+---------------+---------+
|      Nama     | Dimensi |
+---------------+---------+
| random_tensor |  (5, 5) |
|  prime_tensor |  (5, 5) |
+---------------+---------+


# Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator).

In [23]:
aritmatika=PrettyTable(['Aritmatika', 'Hasil'])
aritmatika.add_row(['Tambah',tf.add(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])
aritmatika.add_row(['Kurang',tf.subtract(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])
aritmatika.add_row(['Perkalian',tf.multiply(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])
aritmatika.add_row(['Pembagian', tf.divide(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])
aritmatika.add_row(['Pangkat', tf.pow(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])
print(aritmatika)

+------------+-----------------------------------------------------------------------------------------------+
| Aritmatika |                                             Hasil                                             |
+------------+-----------------------------------------------------------------------------------------------+
|   Tambah   |                                           tf.Tensor(                                          |
|            |                                     [[ 56  74  62  56 105]                                    |
|            |                                      [ 51  59  49 109  27]                                    |
|            |                                      [ 57 125  83 101 105]                                    |
|            |                                      [ 29  22  59  60  63]                                    |
|            |                       [ 50  72  76  78 101]], shape=(5, 5), dtype=int32)                      |
|

In [24]:
# nilai maksimum dan minimum variabel random_tensor

In [25]:
import numpy as np


max_row=tf.argmax(random_tensor,axis=0)
min_row=tf.argmin(random_tensor,axis=0)
minim=np.min(random_tensor)
maxim=np.max(random_tensor)
tabel_min_max=PrettyTable(['Nilai', 'Setiap Index', 'Nilai Variabel Random_tensor'])
tabel_min_max.add_row(['Minimum', min_row,minim])
tabel_min_max.add_row(['Maksimum', max_row,maxim])
print(tabel_min_max)

+----------+-------------------------------------------------+------------------------------+
|  Nilai   |                   Setiap Index                  | Nilai Variabel Random_tensor |
+----------+-------------------------------------------------+------------------------------+
| Minimum  | tf.Tensor([2 3 1 3 1], shape=(5,), dtype=int64) |              4               |
| Maksimum | tf.Tensor([0 2 4 1 0], shape=(5,), dtype=int64) |              88              |
+----------+-------------------------------------------------+------------------------------+


# Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [27]:
Concat=tf.concat([random_tensor,prime_tensor], axis=1)
Concat

<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[54, 69, 55, 45, 88,  2,  5,  7, 11, 17],
       [48, 46, 30, 80,  4,  3, 13, 19, 29, 23],
       [26, 84, 46, 58, 58, 31, 41, 37, 43, 47],
       [27, 17, 52, 19, 20,  2,  5,  7, 41, 43],
       [33, 61, 69, 55, 64, 17, 11,  7, 23, 37]])>

In [28]:
# tampilan kedua variabel yang telah disorting secara descending

In [29]:
random_desc=tf.sort(random_tensor,direction='DESCENDING')

random_desc

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[88, 69, 55, 54, 45],
       [80, 48, 46, 30,  4],
       [84, 58, 58, 46, 26],
       [52, 27, 20, 19, 17],
       [69, 64, 61, 55, 33]])>

In [30]:
prime_desc=tf.sort(prime_tensor,direction='DESCENDING')
prime_desc

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[17, 11,  7,  5,  2],
       [29, 23, 19, 13,  3],
       [47, 43, 41, 37, 31],
       [43, 41,  7,  5,  2],
       [37, 23, 17, 11,  7]])>